-- 코드를 입력하세요
SELECT
    B.TITLE,
    B.BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    date_format(R.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
    ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01'
  AND B.CREATED_DATE <  '2022-11-01'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;